name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for multi-platform builds

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  # Ensure these secrets are set in your GitHub repository settings

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure the deploy job runs after the build job

    steps:
    - name: Set up Azure Kubernetes Service (AKS)
      uses: azure/aks-set-context@v1
      with:
        cluster-name: <your-cluster-name>
        resource-group: <your-resource-group>
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
    - name: Deploy the app to AKS
      run: |
        kubectl apply -f k8s/user-service-deployment.yaml
        kubectl apply -f k8s/user-service-service.yaml
